### ISSUE TITLE
Test failures on mpop 1.2.1

### ISSUE THREAD

**Issue by avalentino** [pytroll/mpop#29]
I'm preparing the new debian package for mpop 1.2.1 and I have the following errors when I run the test suite on debian sid:

```
======================================================================
FAIL: test_project (tests.test_pp_core.TestPPCore)
Test project
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antonio/debian/git/build-area/python-mpop-1.2.1/mpop/tests/test_pp_core.py", line 99, in test_project
    self.assertEquals(new_scene.area_id, area2)
AssertionError: None != 'oGuyfXoY'

======================================================================
FAIL: test_init (tests.test_projector.TestProjector)
Creation of coverage.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/antonio/debian/git/build-area/python-mpop-1.2.1/mpop/tests/test_projector.py", line 76, in test_init
    self.assertEquals(utils.parse_area_file.call_count, 2)
AssertionError: 0 != 2

======================================================================
FAIL: test_project_array (tests.test_projector.TestProjector)
Test the project_array function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/antonio/debian/git/build-area/python-mpop-1.2.1/mpop/tests/test_projector.py", line 171, in test_project_array
    data, "a", fill_value=None)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "/usr/lib/python2.7/dist-packages/six.py", line 718, in raise_from
    raise value
AssertionError: Expected call: ImageContainer(array([[-1.50200251],
       [-0.6686467 ],
       [ 1.18901589]]), 'a', fill_value=None)
Actual call: ImageContainer(array([[-1.50200251],
       [-0.6686467 ],
       [ 1.18901589]]), <MagicMock name='mock.utils.parse_area_file().__getitem__()' id='139760093893840'>, fill_value=None)
```

Also I have an additional error due fact that the `trollsift` module is missing.
Please note that `trollsift` is not listed in the package dependencies in `setup.py`.

**Comment by mraspaud** [comment]
Thanks for the bug report, I will look at it asap.

**Comment by mraspaud** [comment]
Hi @avalentino,

I can't seem to reproduce your error, did you get mpop from pypi or github ?

**Comment by avalentino** [comment]
Hi @mraspaud,
I have just realized that the download script points to  https://github.com/mraspaud/mpop/tags.
Downloaded version 1.2.1.
I assume that it is the same of https://github.com/pytroll/mpop/releases/tag/v1.2.1.

The complete debian package code (including mpop code) can be found at:http://anonscm.debian.org/git/pkg-grass/python-mpop.git (browsable version: http://anonscm.debian.org/gitweb/?p=pkg-grass/python-mpop.git;a=summary)

The build environment is debian sid and64 with 

* python-setuptools,
* python-all,
* python-doc,
* python-numpy,
* python-sphinx,
* python-h5py,
* python-imaging,
* python-mipp,
* python-pyresample,
* python-pyorbital,
* python-netcdf4,
* python-mock

I can post the exact version of each package if you are interested in.

**Comment by mraspaud** [comment]
I see that one of the failing test is tests.test_pp_core.TestPPCore, which is commented out in the test suite. How do you run the tests ?

The way we do it (eg in travis) is to call `python setup.py test`, so we can customize the test suite to our needs.

**Comment by avalentino** [comment]
The test suite was run using the following commands:
```
env PYTHONPATH=. PPP_CONFIG_DIR=debian/etc/mpop python -m unittest discover mpop
env PYTHONPATH=. PPP_CONFIG_DIR=debian/etc/mpop python -m unittest discover test
```

Now I have updated the script to use 

```
python setup.py test
```

and only one test failure remains:

```
======================================================================
FAIL: test_init (mpop.tests.test_projector.TestProjector)
Creation of coverage.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/antonio/debian/git/build-area/python-mpop-1.2.1/mpop/tests/test_projector.py", line 77, in test_init
    utils.parse_area_file.assert_any_call('', in_area_id)
  File "/usr/lib/python2.7/dist-packages/mock/mock.py", line 999, in assert_any_call
    ), cause)
  File "/usr/lib/python2.7/dist-packages/six.py", line 718, in raise_from
    raise value
AssertionError: parse_area_file('', 'pNlJdkUuSRLshqAbpGaf') call not found

----------------------------------------------------------------------
Ran 61 tests in 0.247s

FAILED (failures=1)
```

**Comment by mraspaud** [comment]
@avalentino what version of python are you using ?

**Comment by avalentino** [comment]
System Python v2.7.11

**Comment by mraspaud** [comment]
@avalentino I can't reproduce the bug, but I made an attempt at fixing it in the pre-master branch. Could you try it, and tell me if it works ?

**Comment by avalentino** [comment]
@mraspaud sorry for the late reply
yes, it works now
